### ISSUE TITLE
Pull overall total?

### ISSUE THREAD

**Issue by ShinyRedDino** [Coffee-fueled-deadlines/OSRSBytes#31]
Is there an option to pull the overall total level as well?

**Comment by Coffee-fueled-deadlines** [comment]
It should be:

```
from OSRSBytes import Hiscores

user = Hiscores("Hess")
print(user.skill("total","level"))
```

However, this raises an issue of there being a parsing error in that section of the code that I'll need to address as it outputs incorrect information.

For now you can access the total/overall attributes with this loop:

```
from OSRSBytes import Hiscores

user = Hiscores("Hess")

for value in user.data.split(" "):
    total_info = value.split(",")
    total_rank = total_info[0]
    total_level = total_info[1]
    total_experience = total_info[2]
    
print("Users Total Rank is {}".format(total_rank))
print("Users Total Level is {}".format(total_level))
print("Users Total Experience is {}".format(total_experience))
```

I'll add this to the todo list for version 1.3.1 so that this work around isn't needed.

**Comment by Coffee-fueled-deadlines** [comment]
This has been fixed in [This](https://github.com/Coffee-fueled-deadlines/OSRSBytes/commit/dfa9fcf146f82cae0f735a82a6a5695d73b2ce98) commit.
